replicaCount: 2

image:
  repository: rabbitmq
  tag: "4.1.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672

    - name: management
      port: 15672
      targetPort: 15672

    - name: prometheus
      port: 9419
      targetPort: 9419

serviceAccount:
  enabled: true
  name: ""

rabbitmq:
  username: stauser
  password: stapass

ingress:
  enabled: false

hpa:
  enabled: false

autoscaling:
  enabled: false

metrics:
  enabled: true
  prometheus:
    scrapePort: 9419